### ISSUE TITLE
BadRequestException: Table 'knex_migrations' already exists.

### ISSUE THREAD

**Issue by akarmes** [markusahlstrand/knex-data-api-client#11]
I'm trying to make it work with knex migrations, but it fails with confusing error:

```
BadRequestException: Table 'knex_migrations' already exists.
```

## Context

My migration file
```js
exports.up = function(knex) {
  return knex.schema.createTable('foobar', (table) => {
    table.increments('id');
 })
};

exports.down = function(knex) {
  return knex.schema
    .dropTable('foobar');
};
```

knexfile
```js
const knexDataApiClient = require('knex-aurora-data-api-client');

const config = {
  client: knexDataApiClient.mysql,
  connection: {
    resourceArn: '...',
    secretArn: '...',
    region: '...',
    database: '...',
  },
}

module.exports = {
  development: config,
  staging: config,
  production: config,
};
```

Once I run `knex migrate:latest` it fails with: 
```
BadRequestException: Table 'knex_migrations' already exists
```
Upon checking RDS instance in AWS console, I see that it just created tables "knex_migrations" and "knex_migrations_lock". 

When I try to run `knex migrate:latest`, I get same error.
When I remove those tables and rerun `knex migrate:latest`, I get same error.

**Comment by markusahlstrand** [comment]
Hi @akarmes, 

Did you figure this out what the issue was? I'm not sure if I can recreate it..

**Comment by akarmes** [comment]
I've ending up ditching knex-data-api-client in favor of using direct knex connection to RDS cluster, for migration lambda.

I'll close the issue.
