### ISSUE TITLE
Wrong returning structure PostgreSQL

### ISSUE THREAD

**Issue by deel77** [markusahlstrand/knex-data-api-client#29]
Right now if you use this connector with PostgreSQL and `returning(...)` call [(knex spec)](http://knexjs.org/#Builder-returning)

It is always returning "array of objects" even when it should be just returning "array of values".

Example:
```
knex('books')
  .returning('id')
  .insert({title: 'Slaughterhouse Five'})
```
is returning `[ { id: 1 } ]` instead of expected `[ 1 ]`

Only if you are expecting multiple properties `returning('id','title')` it should return `[ { id: 1, title: 'Slaughterhouse Five' } ]`

Not sure if its problem here or with used "data-api-client", but this connector should comply with Knex specification.

I was expecting to use knex with interchangeable connectors for DataAPI and plain PostgreSQL, but this issue is making it harder.

**Comment by markusahlstrand** [comment]
Thanks for creating the issue! It does indeed look like a bug. Sounds like it should be a quick fix, I'll have a look at it :)

**Comment by markusahlstrand** [comment]
@deel77 did a quick PR to fix this issue. Ideally this should be fixed in the data-api client but as it might take a while it's faster to patch it here first.

The fix isn't very elegant, not sure if there's a better way to do it..

@deel77 Could you check if you think this fix would work for you?
