### ISSUE TITLE
installing extra packages

### ISSUE THREAD

**Issue by davegariepy** [markusahlstrand/knex-data-api-client#35]
hi, thanks for making this.

I'm using the `NodejsFunction` CDK construct which uses parcel to bundle. I had to install a few extra packages including `mysql`, `pg`, `pg-native` and `pg-query-stream`. Is this normal?

thanks

**Comment by markusahlstrand** [comment]
Hi @davegariepy, 

I haven't tried using CDK to package lambdas yet, so I'm not certain how it would work. I typically use serverless to deploy lambdas and have defined some dependencies as external in webpack config to avoid having to add them to the project:

```
    externals: {
      pg: 'commonjs pg',
      mysql: 'commonjs mysql',
      mysql2: 'commonjs mysql2',
      mssql: 'commonjs mssql',
      sqlite3: 'commonjs sqlite3',
      oracledb: 'commonjs oracledb',
      oracle: 'commonjs oracle',
      tedious: 'commonjs tedious',
      'pg-query-stream': 'commonjs pg-query-stream',
      'mssql/package.json': 'commonjs mssql/package.json',
      'mssql/lib/base': 'commonjs mssql/lib/base'
    },
```

Looks like CDK is using parcel for packaging? Can you reproduce the issue by just using Parcel without CDK?

**Comment by davegariepy** [comment]
Hi @markusahlstrand, 

Thanks for the response, this was a problem with parcel. The CDK has recently swapped parcel for esbuild as of 1.75, anyway.

In case anyone finds this, I ended up adding an option to the CDK construct `nodeModules: ["pg", "knex"]`

Thanks!
