### ISSUE TITLE
Json is not returning back as a object

### ISSUE THREAD

**Issue by dleesalestreamsoft** [markusahlstrand/knex-data-api-client#38]
Trying to use data api and found differences in the results.

knex was returning json as object and now I see it being returned as a string.

**Comment by markusahlstrand** [comment]
Are you using the latest version? Thought I just fixed this for json and jsonb..

Could you check the version you're using and post a sample?

**Comment by dleesalestreamsoft** [comment]
After debugging, I found out it is the raw queries having issues.

**Comment by markusahlstrand** [comment]
Ok, that sounds like something I might have missed. Do you have a sample query/data and I can setup a test for it?

**Comment by markusahlstrand** [comment]
I thinks this is fixed in later versions. Re-open if it isn't the case
