### ISSUE TITLE
timestamp not inserting when null

### ISSUE THREAD

**Issue by dleesalestreamsoft** [markusahlstrand/knex-data-api-client#39]
getting this
 invalid input syntax for type timestamp with time zone: "null"

**Comment by markusahlstrand** [comment]
Think I've seen this as well. Do you have a sample query to test with?

**Comment by markusahlstrand** [comment]
Ok, saw that it was a simple insert. Added a test and confirmed that it's a bug. I'll see if I can add a fix for it.

**Comment by markusahlstrand** [comment]
Published a new version (1.4.2) that should fix this issue. Let me know if it works for you.
