### ISSUE TITLE
update with returning not gettting data back

### ISSUE THREAD

**Issue by dleesalestreamsoft** [markusahlstrand/knex-data-api-client#40]
update can have returning * 

but it did not get data back

**Comment by markusahlstrand** [comment]
Yes, added a test for this and it works differently from local pg. I'll see if it's an easy fix.

**Comment by markusahlstrand** [comment]
Published a new version (1.4.1) that should fix this. Could you verify if it works for you?

**Comment by pats110217** [comment]
Hi @markusahlstrand thanks for this module, I also notice for delete that it does not return the deleted data. I can create a PR for this. Thanks

**Comment by markusahlstrand** [comment]
That would be great :)

**Comment by markusahlstrand** [comment]
I'll close this issue as the update is returning data now. @pats110217: I'll make a fix for the deleted data. Hopefully done today.
