### ISSUE TITLE
[DOCS] update install/use docs to mention configuring AWS

### ISSUE THREAD

**Issue by andrewtpoe** [markusahlstrand/knex-data-api-client#5]
## Overview

While attempting to configure this in a project I followed the steps as outlined currently. I added a section to my knexfile and provided the values needed. I received connection refused errors when attempting to actually run migrations/ query against my database.

## Cause

The cause turned out to be 100% my fault. I didn't have AWS initialized or configured in my knexfile. I found the solution by referencing the knexfile within this repo.

## Suggested Solution

I suggest adding a section or expanding the current installation guide to mention that AWS must additionally be configured in your project. This is probably a no-brainer for people experience with AWS, but I'm learning it and this blocked me for far longer than it should have.

**Comment by markusahlstrand** [comment]
I'll add a section with a reference to the data-api-client documentation. Thank!

**Comment by markusahlstrand** [comment]
Updated the docs now and pushed a new version. Do you think we need something more detailed or is this ok?
