### ISSUE TITLE
some properties don't exist when using typescript

### ISSUE THREAD

**Issue by zgheibali** [markusahlstrand/knex-data-api-client#56]
Hello, I'm trying to configure knex for a mysql aurora DB using typescript

I did the configuration as follows:

import knexDataApiClient from "knex-aurora-data-api-client";
import Knex from "knex";

export const knex = Knex({
  client: knexDataApiClient.mysql,
  connection: {
    secretArn: "secret-arn", // Required
    resourceArn: "db-resource-arn", // Required
    database: "db-name",
    region: "eu-west-2",
  },
});

the code editor points out that secretArn, resourceArn, region doesn't exist. However other properties like client and database are working fine. what could be the reason? am I doing the configuration wrong?

Error:  Property x... doesnt not exist on the staticConnection config | connectionConfigProvider
Thank you

**Comment by brian-learningpool** [comment]
Hi @zgheibali, I was wondering why you closed this one?  If you managed to solve it could you share your solution?  I'm seeing the same issue.
