### ISSUE TITLE
Bundle size is 120MB. Looks like it's packaging all dev dependencies

### ISSUE THREAD

**Issue by DanielOrtel** [markusahlstrand/knex-data-api-client#6]
Seems like the node_modules under `test/integration/setup` were accidentally commited. 

In fact, it's publishing the tests to npm to begin with, could maybe use a bundler to handle the process?

**Comment by askarzh** [comment]
One way to move aws-sdk from dependencies to dev dependencies.

**Comment by DanielOrtel** [comment]
it's not related to the aws-sdk, the bundle of this package itself is 120MB due to having all of it's dev dependencies related to testing bundled. You can see this on the [npm page](https://www.npmjs.com/package/knex-aurora-data-api-client) and I've checked locally and the bundle is that big.

**Comment by askarzh** [comment]
Sorry. I didn't understand you before. I care more about production bundle and in this case the aws-sdk should be removed from dependencies.

**Comment by markusahlstrand** [comment]
Sorry, totally missed the notifications for this issue. I'll push a new version. Thanks for opening the issue!

**Comment by markusahlstrand** [comment]
Moved aws-sdk to peer-dependencies (should have been dev-dependencies now that I think about it.. Will move it in the next release) and published a new version which is 267 kB unpacked.

**Comment by DanielOrtel** [comment]
cool, thanks!
