### ISSUE TITLE
TypeScript extension not working

### ISSUE THREAD

**Issue by honarpour** [markusahlstrand/knex-data-api-client#64]
When using the latest [`knex`](https://www.npmjs.com/package/knex) package directly I'm able to write migrations in TypeScript/ES6 and that works.
However, after switching to [`knex-aurora-data-api-client`](https://www.npmjs.com/package/knex-aurora-data-api-client) (which has Knex `0.21.1`), `ts` extension seems to have stopped working. If I get rid of types and ES6, then it works.
Current version of Knex is `0.95.6`, wondering if it's related and/or if the package can be updated to latest.

This is my `knexfile.ts`:
```
const config = {
  client: knexDataApiClient.postgres,
  connection: {
    secretArn: 'arn:aws:secretsmanager:us-east-1:...',
    resourceArn: 'arn:aws:rds:us-east-1:...',
    database: 'mydatabase',
    region: 'us-east-1',
  },
  migrations: {
    config: 'knex_migrations',
    extension: 'ts',
    directory: 'migrations',
    stub: 'migrations.stub.ts',
  },
};
```

The error I get when running `knex migrate:latest`:

![image](https://user-images.githubusercontent.com/4552454/121906929-95f95300-ccf9-11eb-810a-90ef2b79f552.png)

**Comment by markusahlstrand** [comment]
Hi @honarpour,

It should work fine to use either the 0.21 or the 0.96 version of knex. I think the issue might be that there is not es-module version of this package but only a version for cjs. I'm not certain what would be needed to add support for es-modules?

**Comment by honarpour** [comment]
Hey @markusahlstrand!

For ES6 support could add [Babel](https://babeljs.io/docs/en/babel-cli).
The thing is it worked when using Knex directly, that's why I thought might need to update the dependancy.
Main issue is if I refactor to CommonJS, then it throws error on the colons (`:`) for TS types, so can't do TS either.

**Comment by honarpour** [comment]
@markusahlstrand Yup that was the issue. I forked the repo and updated Knex to latest and am able to run migrations written in TypeScript and ES6 out of the box. I can open a PR with the update if that works.

**Comment by markusahlstrand** [comment]
@honarpour So just by updating the knex version it worked? I didn't want to bump it because then for instance objection won't work any longer. As it's just a peer dependency it should work fine with an app that has a newer version of knex installed as well.. Or am I missing something?

**Comment by honarpour** [comment]
Yeah updating version worked for migrations but importing Knex in Lambdas broke.
Seems like I was missing something... for some reason I got version clashes when installing the latest Knex in consuming project, but just tried it again and it's working everywhere!
