### ISSUE TITLE
less documentation

### ISSUE THREAD

**Issue by rabimatuag** [markusahlstrand/knex-data-api-client#67]
data-api-client contributor suggest that, first build the query with knex and use that in data-api query,found this package but has no more documentation so please could you give more information about this package
and what here  doSomething() actually does what kind of action could be execute with it

**Comment by markusahlstrand** [comment]
Hi, sorry for the late response. 

The idea with the package is that it should just exactly like the postgres of mysql version of knex but that it communicates via the data-api http endpoint.
