### ISSUE TITLE
Support for knex-migrate toolkit 

### ISSUE THREAD

**Issue by DanielOrtel** [markusahlstrand/knex-data-api-client#7]
This package really solved a lot of problems for me, so first off, thanks for all the effort with this, I'm really liking it so far. Sadly though I had to get rid of the [knex-migrate](https://github.com/sheerun/knex-migrate) utility, since this package doesn't seem to support it, and i'd be nice to have both. 

While migrations work just fine with plain `knex.js`, trying to use `knex-migrate` causes the following error: `expecting an array or an iterable object but got [object Null]`. 

After investigating some, I think this is due to the fact `knex-migrate` uses `pluck`, which is not mapped in the `data-api` `processResponse`, though I'm not all that familiar with all this, so I may be mistaken.

**Comment by markusahlstrand** [comment]
Haven't used the knex-migate utility but looks nice. I'll see if I can check it out :)

**Comment by markusahlstrand** [comment]
Finally got around to have a look at this issue. Had to patch the errors returned from the data-client and add a very basic pluck support. Will be fixed by #32
