### ISSUE TITLE
Value of infinity in timestamp columns breaks > v.1.5.0

### ISSUE THREAD

**Issue by jaska120** [markusahlstrand/knex-data-api-client#86]
**Problem**
I have just tried to upgrade from v.1.5.0 to the latest available version to use fresh version of knex. However, [181e410b9dd60abb8d6fffe4f5d9c54765c39a8a](https://github.com/markusahlstrand/knex-data-api-client/commit/181e410b9dd60abb8d6fffe4f5d9c54765c39a8a#diff-e9726d469bba0bec8608c095ad5c361aeb95ea53afadd7ab44b462a2eb5e7467R11) seems to break the possible value of `infinity` in PostgreSQL database, which is valid value according to the [spec](https://www.postgresql.org/docs/9.0/datatype-datetime.html).

**Background**
"**8.5.1.4. Special Values**
PostgreSQL supports several special date/time input values for convenience, as shown in [Table 8-13](https://www.postgresql.org/docs/9.0/datatype-datetime.html#DATATYPE-DATETIME-SPECIAL-TABLE). The values infinity and -infinity are specially represented inside the system and will be displayed unchanged; but the others are simply notational shorthands that will be converted to ordinary date/time values when read. (In particular, now and related strings are converted to a specific time value as soon as they are read.) All of these values need to be enclosed in single quotes when used as constants in SQL commands."

**What is causing it**
Now, the timestamp value of `"+292278994-08-16 23:00:00"` (representing the value of infinity) is passed to the match method in https://github.com/markusahlstrand/knex-data-api-client/blob/master/src/types.js#L15 and the array destructor fails with error of "object null is not iterable (cannot read property Symbol(Symbol.iterator)".

I am not sure who is responsible for converting infinity value to `"+292278994-08-16 23:00:00"`: AWS, data-api-client or this project. Should this library take into account the possibility of inifinity values? With version 1.5.0 the infinity values are working as expected.

**Comment by jaska120** [comment]
@markusahlstrand Do you have input on the matter? Changing the regex [here](https://github.com/markusahlstrand/knex-data-api-client/blob/master/src/types.js#L15) would allow a quick fix, but should this be fixed in the upstream?

**Comment by markusahlstrand** [comment]
Hi @jaska120 and thanks for the issue!

I think we should try to match the behaviour of the normal PG adapter for knex.. Do you know what it would return?

**Comment by jaska120** [comment]
I just tested this with our unit tests using [pg](https://www.npmjs.com/package/pg) client with Knex in local environment.

If the date is Infinity in PostgreSQL database, pg client is returning a numeric value of `Infinity`. I guess the same would apply for negative Infinity as well.

**Comment by jaska120** [comment]
@markusahlstrand I am pinging because this is blocking us to upgrade to latest. Do you have an input which way we should tackle the issue? Show we just change the regex as linked in my previous comment? If you are in a hurry, I can provide a PR to fix the issue, but I would like to have your input where in your opinion this should be fixed?

**Comment by markusahlstrand** [comment]
Hi and sorry for the delay. Maybe it's best to have a pretty explicit check for the infinity values? Maybe define Infinity and -Infinity as constants and do a comparison?

It should be a pretty quick fix, would just like to add two tests for it so we keep track of it. You're welcome to make a PR for it, otherwise I'll try to get it done this evening or tomorrow.

**Comment by jaska120** [comment]
> Hi and sorry for the delay. Maybe it's best to have a pretty explicit check for the infinity values? Maybe define Infinity and -Infinity as constants and do a comparison?
> 
> It should be a pretty quick fix, would just like to add two tests for it so we keep track of it. You're welcome to make a PR for it, otherwise I'll try to get it done this evening or tomorrow.

I think the problem is that the upstream data-api-client returns the value in the database as string of "+292278994-08-16 23:00:00" which is a malfunction in itself (this is how a perceived it). Therefore, the comparison needs to be made against wrong presentation of stringified timestamp and the solution will not be explicit per se.

If you find time, great! Otherwise I will look into it at the end of the week. Anyway, thank you for your quick replies, much appreciated!

**Comment by markusahlstrand** [comment]
Thanks for the PR :) I did a few minor changes and created a new PR #88. For now I just kept the check for the year which seems to be sufficient? Let me know if you see any issues with this solution.
